In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
import sys
sys.path.append('../')
%matplotlib inline

pd.set_option('display.max_rows', 50)
pd.set_option('display.max_columns', None)

In [2]:
dataset_path = '../dataset/dbghs/九州/'

In [3]:
list_df = [pd.read_excel(str(p)) for p in Path(dataset_path).glob('*.xls')]
df_kyusyu = pd.concat(list_df)
df_kyusyu.head()

,都道府県名,所在地,東経（゜）,東経（′）,東経（″),北緯（゜）,北緯（′）,北緯（″),標高（ｍ）,水源種別,利用目的,井戸深度,採水標高,気温,水温,湧出量,水質（外観臭味）,ｐＨ,ＲｐＨ,Ｒｎ(マッヘ),比重,密度,蒸発残留物,電気伝導度,水比抵抗,ＥＨ,ＫＭｎＯ４消費,Ｈ＋,Ｌｉ＋,Na＋,Ｋ＋,Ｒｂ＋,Ｃｓ＋,ＮＨ４＋,Ｍｇ２＋,Ｃａ２＋,Ｓｒ２＋,Ｂａ２＋,Ａｌ３＋,Ｍｎ２＋,Ｆｅ２＋,Ｆｅ３＋,Ｔ−Ｆｅ,Ｃｕ２＋,Ｚｎ２＋,Ｐｂ２＋,Ｓｉ４＋,Ｆ−,Ｃｌ−,Ｂｒ−,I−,OH−,ＮＯ２−,ＮＯ３−,ＨＳ−,Ｓ２Ｏ３2−,ＨＳＯ４−,ＳＯ４２−,ＳＯ３２−,Ｈ２ＰＯ４−,ＨＰＯ４２−,ＰＯ４３−,ＨＣＯ３−,ＣＯ３２−,ＨＳｉＯ３−,ＳｉＯ３２−,ＢＯ２−,Ｈ２ＳＯ４,Ｈ３ＰＯ４,ＨＡｓＯ２,ＡｓＯ２-,ＳｉO２,Ｈ２ＳｉＯ３,ＨＢＯ２,dis.O2,Free H2S,free CO2,Ｔ−ＣＯ２,Ｔ−Ａｓ,Ｔ−Ｈｇ,Ｔ−Ｐ,Ｔ−Ｂ,単位,調査日,文献名,free H2s,free Co2,dis.co2,free H2S,ｄｉｓ．０２,ｆｒｅｅ Ｈ２Ｓ,ｆｒｅｅ ＣＯ２,Ｅh,freeCO2,Free H2s
0,佐賀県,有明町廻里津,130.0,7.0,20.0,33.0,9.0,0.0,NaN,井戸,用水,NaN,NaN,NaN,23.6,NaN,NaN,7.3,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.7,NaN,NaN,16.0,4.9,NaN,NaN,0.1,4.6,8.0,NaN,NaN,NaN,NaN,0.06,0.05,NaN,NaN,NaN,NaN,NaN,NaN,7.8,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,67.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,68.6,NaN,NaN,NaN,NaN,3.5,NaN,NaN,NaN,0.13,NaN,NaN,1960/1,"筑後川下流平野の地下水,地調月報,1961",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,佐賀県,白石町,130.0,9.0,0.0,33.0,9.0,40.0,NaN,井戸,用水,NaN,NaN,NaN,20.0,NaN,NaN,7.3,7.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.8,NaN,NaN,24.9,7.0,NaN,NaN,0.2,4.0,6.8,NaN,NaN,NaN,NaN,0.15,0.00,NaN,NaN,NaN,NaN,NaN,NaN,7.8,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,86.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63.4,NaN,NaN,NaN,NaN,4.4,NaN,NaN,NaN,0.37,NaN,NaN,1960/1,"筑後川下流平野の地下水,地調月報,1961",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,佐賀県,白石町,130.0,8.0,30.0,33.0,10.0,50.0,NaN,井戸,用水,NaN,NaN,NaN,20.2,NaN,NaN,7.3,7.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.4,NaN,NaN,17.4,5.7,NaN,NaN,0.0,3.6,7.4,NaN,NaN,NaN,NaN,0,0.05,NaN,NaN,NaN,NaN,NaN,NaN,10.7,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,61.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,68.6,NaN,NaN,NaN,NaN,3.5,NaN,NaN,NaN,0.14,NaN,NaN,1960/1,"筑後川下流平野の地下水,地調月報,1961",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,佐賀県,福富町,130.0,11.0,20.0,33.0,11.0,0.0,NaN,井戸,用水,NaN,NaN,NaN,21.6,NaN,Ｈ2Ｓ臭,7.2,7.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.6,NaN,NaN,259.5,24.9,NaN,NaN,7.0,41.4,49.8,NaN,NaN,NaN,NaN,0.11,0.00,NaN,NaN,NaN,NaN,NaN,NaN,419.1,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,297.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.65,NaN,NaN,1960/1,"筑後川下流平野の地下水,地調月報,1961",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,佐賀県,牛津町,130.0,12.0,0.0,33.0,14.0,20.0,NaN,井戸,用水,151.5,NaN,NaN,19.2,NaN,NaN,7.7,7.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.7,NaN,NaN,26.1,1.7,NaN,NaN,0.3,5.2,18.6,NaN,NaN,NaN,NaN,0,0.02,NaN,NaN,NaN,NaN,NaN,NaN,12.1,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,113.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.4,NaN,NaN,NaN,NaN,1.7,NaN,NaN,NaN,0.16,NaN,NaN,1960/1,"筑後川下流平野の地下水,地調月報,1961",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df_kyusyu.describe()

,東経（゜）,東経（′）,東経（″),北緯（゜）,北緯（′）,北緯（″),標高（ｍ）,採水標高,気温,水温,ｐＨ,ＲｐＨ,Ｒｎ(マッヘ),比重,密度,蒸発残留物,電気伝導度,水比抵抗,ＥＨ,ＫＭｎＯ４消費,Ｈ＋,Ｌｉ＋,Na＋,Ｋ＋,Ｒｂ＋,Ｃｓ＋,ＮＨ４＋,Ｍｇ２＋,Ｃａ２＋,Ｓｒ２＋,Ｂａ２＋,Ａｌ３＋,Ｍｎ２＋,Ｆｅ３＋,Ｔ−Ｆｅ,Ｃｕ２＋,Ｚｎ２＋,Ｐｂ２＋,Ｓｉ４＋,Ｆ−,Ｃｌ−,Ｂｒ−,I−,OH−,ＮＯ２−,ＮＯ３−,ＨＳ−,Ｓ２Ｏ３2−,ＨＳＯ４−,ＳＯ４２−,ＳＯ３２−,Ｈ２ＰＯ４−,ＨＰＯ４２−,ＰＯ４３−,ＨＣＯ３−,ＣＯ３２−,ＨＳｉＯ３−,ＳｉＯ３２−,ＢＯ２−,Ｈ２ＳＯ４,Ｈ３ＰＯ４,ＨＡｓＯ２,ＡｓＯ２-,ＳｉO２,Ｈ２ＳｉＯ３,ＨＢＯ２,dis.O2,Free H2S,free CO2,Ｔ−ＣＯ２,Ｔ−Ａｓ,Ｔ−Ｈｇ,Ｔ−Ｐ,Ｔ−Ｂ,free H2s,free Co2,dis.co2,free H2S,ｄｉｓ．０２,ｆｒｅｅ Ｈ２Ｓ,ｆｒｅｅ ＣＯ２,Ｅh,freeCO2,Free H2s
count,1536.000000,1536.000000,1536.000000,1536.000000,1536.000000,1536.000000,115.000000,58.000000,662.000000,2152.000000,2167.000000,930.000000,62.000000,553.000000,0.0,1072.000000,158.000000,259.000000,2.000000,430.000000,61.000000,417.000000,1969.000000,1876.000000,110.000000,110.000000,931.000000,1968.000000,1992.000000,102.000000,10.000000,508.000000,1058.000000,213.000000,1217.000000,244.000000,223.000000,155.000000,145.000000,695.000000,2219.000000,482.000000,341.00000,231.000000,282.000000,132.000000,150.000000,171.000000,42.000000,1916.000000,0.0,90.000000,186.000000,0.0,1917.000000,588.000000,256.000000,18.00000,180.000000,22.000000,36.000000,170.000000,42.000000,604.000000,578.000000,453.000000,27.000000,7.000000,415.000000,121.000000,183.000000,121.000000,146.000000,249.000000,119.000000,156.000000,39.000000,255.000000,18.000000,0.0,26.000000,245.000000,478.000000,63.000000
mean,130.052734,29.025391,27.996745,32.087240,28.162760,26.775391,331.700870,-404.672414,20.589728,41.658820,7.184061,7.623484,5.602097,1.002343,NaN,2735.858516,697.937658,5811.621622,-230.000000,9.511093,3.433144,2.001031,707.096823,50.120287,0.268364,0.175545,2.732267,55.930095,94.369566,7.881176,45.650000,5.781339,0.804888,1.912535,2.696725,0.027656,0.144619,0.072000,46.281379,1.972173,1084.995761,9.109400,0.96190,0.834977,0.015004,4.060083,0.650631,15.116825,87.823333,181.633394,NaN,0.538522,0.754737,NaN,320.153991,34.127512,4.001391,0.04150,3.339378,4.228636,0.913333,0.272947,0.046024,87.128084,96.888375,19.294276,3.089630,0.281429,77.567421,273.747107,70.302470,1.440953,0.367671,4.642490,0.246723,224.287897,0.803077,2.304416,1.398333,NaN,7.323077,154.902041,118.882751,4.733333
std,0.764322,16.004275,17.140557,1.226289,17.877858,17.445933,255.485004,178.740564,7.147767,24.917062,1.392366,1.216101,6.921782,0.005208,NaN,5159.575166,1054.015622,3554.386807,14.142136,15.637845,4.668108,4.321481,1459.816556,101.209601,0.325496,0.214624,6.709274,150.806360,226.060094,14.460712,60.718938,30.680399,4.151739,16.731275,11.264828,0.065760,0.391932,0.293307,19.694077,3.052885,2629.518075,12.240993,4.71902,3.305008,0.134236,7.735249,0.802347,188.443456,124.807190,370.362230,NaN,1.382298,2.901323,NaN,481.219619,494.145254,8.522449,0.14917,6.844450,7.747368,1.115580,0.549824,0.051098,92.976160,91.014993,82.945390,2.701173,0.605808,243.218712,359.917690,624.208262,4.708921,0.653186,5.677412,1.151862,487.747728,1.264304,17.406622,2.124015,NaN,10.817405,87.480528,519.294299,14.091258
min,125.000000,0.000000,0.000000,24.000000,0.000000,0.000000,2.700000,-675.000000,-0.500000,2.000000,1.250000,1.700000,0.020000,0.997200,NaN,0.147000,89.300000,200.000000,-240.000000,0.000000,0.000000,0.000000,1.260000,0.010000,0.000000,0.000000,0.000000,0.000000,0.000000,0.050000,0.100000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.200000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.010000,0.010000,0.030000,0.000000,NaN,0.000000,0.010000,NaN,0.000000,0.000000,0.001000,0.00100,0.000000,0.100000,0.108000,0.000000,0.000000,0.001000,1.240000,0.000000,0.000000,0.002000,0.000000,18.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.100000,0.000000,0.000000,NaN,0.000000,-195.000000,0.000000,0.000000
25%,130.000000,13.000000,12.000000,32.000000,12.000000,10.000000,120.000000,-531.250000,14.925000,20.000000,6.700000,7.400000,0.775000,0.998800,NaN,229.000000,163.125000,3100.000000,-235.000000,0.800000,0.210000,0.050000,21.900000,2.900000,0.052500,0.030000,0.100000,1.700000,8.230000,0.300000,0.150000,0.060000,0.020000,0.010000,0.060000,0.000000,0.010000,0.010000,33.600000,0.420000,10.465000,0.280000,0.02000,0.010000,0.000000,0.140000,0.162500,0.020000,7.737500,7.092500,NaN,0.020000,0.031000,NaN,79.360000,0.019500,0.219750,0.00400,0.070000,0.500000,0.341500,0.010000,0.010000,33.275000,37.212500,1.640000,0.075000,0.003500,2.735000,51.400000,0.032500,0.000200,0.050000,0.880000,0.000000,21.200000,0.255000,0.030000,0.155000,NaN,0.000000,110.000000,8.150000,0.200000
50%,130.000000,32.000000,30.000000,32.000000,26.000000,27.000000,285.000000,-450.000000,21.500000,36.250000,7.300000,7.800000,2.460000,1.000200,NaN,558.000000,407.500000,5000.000000,-230.000000,2.400000,1.500000,0.470000,125.000000,6.900000,0.140000,0.080000,0.480000,6.100000,18.795000,2.100000,4.200000,0.240000,0.140000,0.050000,0.250000,0.010000,0.040000,0.010000,43.500000,1.000000,43.900000,2.200000,0.10000,0.040000,0.000000,0.553000,0.355000,0.040000,29.100000,24.425000,NaN,0.065000,0.100000,NaN,154.000000,1.410000,1.028500,0.00650,0.799500,0.750000,0.582500,0.065000,0.032000,57.250000,64.885000,6.285000,3.660000,0.009000,10.600000,141.000000,0.400000,0.000400,0.135000,2.730000,0.000000,66.950000,0.410000,0.360000,0.235000,NaN,0.000000,165.000000,25.450000,0.400000
75%,130.000000,41.000000,40.000000,33.000000,44.000000,40.000000,538.000000,-281.250000,26.475000,54.000000,8.050000,8.300000,9.007500,1.004200,NaN,1891.000000,789.250000,8000.000000,-225.000000,12.750000,5.000000,2.740000,495.000000,32.275000,0.340000,0.260000,2.265000,21.700000,74.100000,4.000000,94.025000,0.793500,0.650000,0.170000,0.970000,0.030000,0.120000,0.050000,58.400000,2.200000,414.400000,16.175000,0.31000,0.330000,0.000000,5.302500,0.745000,0.300000,106.050000,169.125000,NaN,0.315000,0.281500,NaN,341.000000,18.700000,4.028500,0.00875,3.135000,4.057500,0.960250,0.359750,0.064000,117.000000,121.275000,16.000000,5.555000,0.156000,34.744000,332.000000,2.350000,0.000800,0.300000,6.500000,0.000000,188.750000,0.580000,1.400000,1.282500,NaN,11.875000,210.000000,95.340000,1.500000
max,131.000000,59.000000,59.000000,33.000000,59.000000,59.000000,970.000000,24.000000,35.000000,105.000000,10.060000,9.900000,26.100000,1.029700,NaN,34970.000000,9850.000000,18000.000000,-220.000000,94.800000,25.200000,55.600000,10300.000000,913.000000,1.270000,1.270000,105.300000,1859.000000,2752.000000,90.400000,165.600000,412.630000,110.000000,235.500000,239.140000,0.700000,3.930000,3.500000,91.100000,35.000000,18960.000000,62.300000,50.40000,35.610000,2.140000,63.000000,3.760000,2464.662000,465.800000,5140.000000,NaN,8.200000,27.400000,NaN,4530.000000,11980.000000,78.340000,0.63900,38.450000,33.540000,5.380000,5.600000,0.214000,809.000000,707.300000,1696.000000,6.700000,1.640000,2566.000000,1906.000000,8380.000000,22.100000,5.000000,42.900000,10.200000,2410.000000,6.230000,275.710000,6.210000,NaN,33.400000,450.000000,10750.000000,100.700000

## データ欠損率

データがどれだけ欠損しているか.

まずはgoogleマップAPIと連携を取りたいので座標データが残っているサンプルのみを抽出.

In [5]:
def NA_counter(x_df):
    n_nan = x_df.isnull().sum()
    x_df_dtype = x_df.dtypes
    percent_nan = n_nan/len(x_df)
    return pd.DataFrame([n_nan, percent_nan,x_df_dtype]).rename({0:'n_nan', 1:'%', 2:'dtype'}) 

na_df = NA_counter(df_kyusyu)
na_df

,都道府県名,所在地,東経（゜）,東経（′）,東経（″),北緯（゜）,北緯（′）,北緯（″),標高（ｍ）,水源種別,利用目的,井戸深度,採水標高,気温,水温,湧出量,水質（外観臭味）,ｐＨ,ＲｐＨ,Ｒｎ(マッヘ),比重,密度,蒸発残留物,電気伝導度,水比抵抗,ＥＨ,ＫＭｎＯ４消費,Ｈ＋,Ｌｉ＋,Na＋,Ｋ＋,Ｒｂ＋,Ｃｓ＋,ＮＨ４＋,Ｍｇ２＋,Ｃａ２＋,Ｓｒ２＋,Ｂａ２＋,Ａｌ３＋,Ｍｎ２＋,Ｆｅ２＋,Ｆｅ３＋,Ｔ−Ｆｅ,Ｃｕ２＋,Ｚｎ２＋,Ｐｂ２＋,Ｓｉ４＋,Ｆ−,Ｃｌ−,Ｂｒ−,I−,OH−,ＮＯ２−,ＮＯ３−,ＨＳ−,Ｓ２Ｏ３2−,ＨＳＯ４−,ＳＯ４２−,ＳＯ３２−,Ｈ２ＰＯ４−,ＨＰＯ４２−,ＰＯ４３−,ＨＣＯ３−,ＣＯ３２−,ＨＳｉＯ３−,ＳｉＯ３２−,ＢＯ２−,Ｈ２ＳＯ４,Ｈ３ＰＯ４,ＨＡｓＯ２,ＡｓＯ２-,ＳｉO２,Ｈ２ＳｉＯ３,ＨＢＯ２,dis.O2,Free H2S,free CO2,Ｔ−ＣＯ２,Ｔ−Ａｓ,Ｔ−Ｈｇ,Ｔ−Ｐ,Ｔ−Ｂ,単位,調査日,文献名,free H2s,free Co2,dis.co2,free H2S,ｄｉｓ．０２,ｆｒｅｅ Ｈ２Ｓ,ｆｒｅｅ ＣＯ２,Ｅh,freeCO2,Free H2s
n_nan,2,786,724,724,724,724,724,724,2145,2,2,1588,2202,1598,108,1649,2233,93,1330,2198,1707,2260,1188,2102,2001,2258,1830,2199,1843,291,384,2150,2150,1329,292,268,2158,2250,1752,1202,1448,2047,1043,2016,2037,2105,2115,1565,41,1778,1919,2029,1978,2128,2110,2089,2218,344,2260,2170,2074,2260,343,1672,2004,2242,2080,2238,2224,2090,2218,1656,1682,1807,2233,2253,1845,2139,2077,2139,2114,2011,1441,220,2,2141,2104,2221,2005,2242,2260,2234,2015,1782,2197
%,0.000884956,0.347788,0.320354,0.320354,0.320354,0.320354,0.320354,0.320354,0.949115,0.000884956,0.000884956,0.702655,0.974336,0.70708,0.0477876,0.729646,0.988053,0.0411504,0.588496,0.972566,0.75531,1,0.525664,0.930088,0.885398,0.999115,0.809735,0.973009,0.815487,0.128761,0.169912,0.951327,0.951327,0.588053,0.129204,0.118584,0.954867,0.995575,0.775221,0.531858,0.640708,0.905752,0.461504,0.892035,0.901327,0.931416,0.935841,0.692478,0.0181416,0.786726,0.849115,0.897788,0.875221,0.941593,0.933628,0.924336,0.981416,0.152212,1,0.960177,0.917699,1,0.15177,0.739823,0.886726,0.992035,0.920354,0.990265,0.984071,0.924779,0.981416,0.732743,0.744248,0.799558,0.988053,0.996903,0.816372,0.94646,0.919027,0.94646,0.935398,0.889823,0.637611,0.0973451,0.000884956,0.947345,0.930973,0.982743,0.887168,0.992035,1,0.988496,0.891593,0.788496,0.972124
dtype,object,object,float64,float64,float64,float64,float64,float64,float64,object,object,object,float64,float64,float64,object,object,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,object,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,object,object,object,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64

In [6]:
df_kyusyu_grid = df_kyusyu[~pd.isna(df_kyusyu['東経（゜）'])]
df_kyusyu_grid.head(4)

,都道府県名,所在地,東経（゜）,東経（′）,東経（″),北緯（゜）,北緯（′）,北緯（″),標高（ｍ）,水源種別,利用目的,井戸深度,採水標高,気温,水温,湧出量,水質（外観臭味）,ｐＨ,ＲｐＨ,Ｒｎ(マッヘ),比重,密度,蒸発残留物,電気伝導度,水比抵抗,ＥＨ,ＫＭｎＯ４消費,Ｈ＋,Ｌｉ＋,Na＋,Ｋ＋,Ｒｂ＋,Ｃｓ＋,ＮＨ４＋,Ｍｇ２＋,Ｃａ２＋,Ｓｒ２＋,Ｂａ２＋,Ａｌ３＋,Ｍｎ２＋,Ｆｅ２＋,Ｆｅ３＋,Ｔ−Ｆｅ,Ｃｕ２＋,Ｚｎ２＋,Ｐｂ２＋,Ｓｉ４＋,Ｆ−,Ｃｌ−,Ｂｒ−,I−,OH−,ＮＯ２−,ＮＯ３−,ＨＳ−,Ｓ２Ｏ３2−,ＨＳＯ４−,ＳＯ４２−,ＳＯ３２−,Ｈ２ＰＯ４−,ＨＰＯ４２−,ＰＯ４３−,ＨＣＯ３−,ＣＯ３２−,ＨＳｉＯ３−,ＳｉＯ３２−,ＢＯ２−,Ｈ２ＳＯ４,Ｈ３ＰＯ４,ＨＡｓＯ２,ＡｓＯ２-,ＳｉO２,Ｈ２ＳｉＯ３,ＨＢＯ２,dis.O2,Free H2S,free CO2,Ｔ−ＣＯ２,Ｔ−Ａｓ,Ｔ−Ｈｇ,Ｔ−Ｐ,Ｔ−Ｂ,単位,調査日,文献名,free H2s,free Co2,dis.co2,free H2S,ｄｉｓ．０２,ｆｒｅｅ Ｈ２Ｓ,ｆｒｅｅ ＣＯ２,Ｅh,freeCO2,Free H2s
0,佐賀県,有明町廻里津,130.0,7.0,20.0,33.0,9.0,0.0,NaN,井戸,用水,NaN,NaN,NaN,23.6,NaN,NaN,7.3,7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.7,NaN,NaN,16.0,4.9,NaN,NaN,0.1,4.6,8.0,NaN,NaN,NaN,NaN,0.06,0.05,NaN,NaN,NaN,NaN,NaN,NaN,7.8,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,67.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,68.6,NaN,NaN,NaN,NaN,3.5,NaN,NaN,NaN,0.13,NaN,NaN,1960/1,"筑後川下流平野の地下水,地調月報,1961",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,佐賀県,白石町,130.0,9.0,0.0,33.0,9.0,40.0,NaN,井戸,用水,NaN,NaN,NaN,20.0,NaN,NaN,7.3,7.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.8,NaN,NaN,24.9,7.0,NaN,NaN,0.2,4.0,6.8,NaN,NaN,NaN,NaN,0.15,0.00,NaN,NaN,NaN,NaN,NaN,NaN,7.8,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,86.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63.4,NaN,NaN,NaN,NaN,4.4,NaN,NaN,NaN,0.37,NaN,NaN,1960/1,"筑後川下流平野の地下水,地調月報,1961",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,佐賀県,白石町,130.0,8.0,30.0,33.0,10.0,50.0,NaN,井戸,用水,NaN,NaN,NaN,20.2,NaN,NaN,7.3,7.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.4,NaN,NaN,17.4,5.7,NaN,NaN,0.0,3.6,7.4,NaN,NaN,NaN,NaN,0,0.05,NaN,NaN,NaN,NaN,NaN,NaN,10.7,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,61.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,68.6,NaN,NaN,NaN,NaN,3.5,NaN,NaN,NaN,0.14,NaN,NaN,1960/1,"筑後川下流平野の地下水,地調月報,1961",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,佐賀県,福富町,130.0,11.0,20.0,33.0,11.0,0.0,NaN,井戸,用水,NaN,NaN,NaN,21.6,NaN,Ｈ2Ｓ臭,7.2,7.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.6,NaN,NaN,259.5,24.9,NaN,NaN,7.0,41.4,49.8,NaN,NaN,NaN,NaN,0.11,0.00,NaN,NaN,NaN,NaN,NaN,NaN,419.1,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,297.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.65,NaN,NaN,1960/1,"筑後川下流平野の地下水,地調月報,1961",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df_kyusyu_grid.describe()

,東経（゜）,東経（′）,東経（″),北緯（゜）,北緯（′）,北緯（″),標高（ｍ）,採水標高,気温,水温,ｐＨ,ＲｐＨ,Ｒｎ(マッヘ),比重,密度,蒸発残留物,電気伝導度,水比抵抗,ＥＨ,ＫＭｎＯ４消費,Ｈ＋,Ｌｉ＋,Na＋,Ｋ＋,Ｒｂ＋,Ｃｓ＋,ＮＨ４＋,Ｍｇ２＋,Ｃａ２＋,Ｓｒ２＋,Ｂａ２＋,Ａｌ３＋,Ｍｎ２＋,Ｆｅ３＋,Ｔ−Ｆｅ,Ｃｕ２＋,Ｚｎ２＋,Ｐｂ２＋,Ｓｉ４＋,Ｆ−,Ｃｌ−,Ｂｒ−,I−,OH−,ＮＯ２−,ＮＯ３−,ＨＳ−,Ｓ２Ｏ３2−,ＨＳＯ４−,ＳＯ４２−,ＳＯ３２−,Ｈ２ＰＯ４−,ＨＰＯ４２−,ＰＯ４３−,ＨＣＯ３−,ＣＯ３２−,ＨＳｉＯ３−,ＳｉＯ３２−,ＢＯ２−,Ｈ２ＳＯ４,Ｈ３ＰＯ４,ＨＡｓＯ２,ＡｓＯ２-,ＳｉO２,Ｈ２ＳｉＯ３,ＨＢＯ２,dis.O2,Free H2S,free CO2,Ｔ−ＣＯ２,Ｔ−Ａｓ,Ｔ−Ｈｇ,Ｔ−Ｐ,Ｔ−Ｂ,free H2s,free Co2,dis.co2,free H2S,ｄｉｓ．０２,ｆｒｅｅ Ｈ２Ｓ,ｆｒｅｅ ＣＯ２,Ｅh,freeCO2,Free H2s
count,1536.000000,1536.000000,1536.000000,1536.000000,1536.000000,1536.000000,115.000000,0.0,566.000000,1492.000000,1513.000000,601.000000,62.000000,543.000000,0.0,809.000000,80.000000,47.000000,0.0,277.000000,58.000000,332.000000,1454.000000,1452.000000,110.000000,110.000000,780.000000,1445.000000,1466.000000,102.000000,10.000000,494.000000,892.000000,116.000000,1019.000000,244.000000,223.000000,155.000000,145.000000,684.000000,1520.000000,457.000000,314.000000,225.000000,209.000000,80.000000,150.000000,171.000000,42.000000,1396.000000,0.0,90.000000,186.000000,0.0,1379.000000,470.000000,256.000000,18.00000,172.000000,22.000000,36.000000,170.000000,42.000000,485.000000,578.000000,389.000000,22.000000,1.000,325.000000,55.000000,183.000000,121.000000,104.000000,249.000000,110.000000,122.000000,7.000000,254.000000,18.000000,0.0,26.000000,37.000000,276.000000,60.000000
mean,130.052734,29.025391,27.996745,32.087240,28.162760,26.775391,331.700870,NaN,21.120495,43.792225,7.270615,7.483045,5.602097,1.002381,NaN,3422.695413,507.551875,4847.446809,NaN,6.925668,3.610534,1.858795,815.971324,56.876337,0.268364,0.175545,2.561059,66.516329,109.227128,7.881176,45.650000,5.683354,0.821351,3.113621,3.106765,0.027656,0.144619,0.072000,46.281379,1.988918,1310.670207,8.884337,1.042306,0.853660,0.019713,4.350400,0.650631,15.116825,87.823333,207.753788,NaN,0.538522,0.754737,NaN,330.780371,38.861051,4.001391,0.04150,3.390023,4.228636,0.913333,0.272947,0.046024,101.160540,96.888375,15.683087,2.390909,0.251,84.704006,287.612727,70.302470,1.440953,0.160817,4.642490,0.120545,276.426230,1.167143,2.313488,1.398333,NaN,7.323077,90.297297,172.286214,4.970000
std,0.764322,16.004275,17.140557,1.226289,17.877858,17.445933,255.485004,NaN,7.265742,23.915182,1.418996,1.448070,6.921782,0.005244,NaN,5685.305665,715.530518,3229.878493,NaN,12.805094,4.720919,3.857300,1596.306490,107.274598,0.325496,0.214624,6.357027,170.868054,254.902914,14.460712,60.718938,30.702968,4.035755,22.532428,12.258051,0.065760,0.391932,0.293307,19.694077,3.066988,2945.793464,12.336502,4.910005,3.346933,0.155720,8.342521,0.802347,188.443456,124.807190,402.916962,NaN,1.382298,2.901323,NaN,498.981129,552.599476,8.522449,0.14917,6.950604,7.747368,1.115580,0.549824,0.051098,95.692539,91.014993,26.343857,2.489821,NaN,269.127259,349.602017,624.208262,4.708921,0.201273,5.677412,0.462900,539.402411,2.244005,17.440384,2.124015,NaN,10.817405,125.355243,676.468848,14.403605
min,125.000000,0.000000,0.000000,24.000000,0.000000,0.000000,2.700000,NaN,-0.500000,6.900000,1.600000,1.700000,0.020000,0.997200,NaN,0.147000,89.300000,200.000000,NaN,0.000000,0.000000,0.000000,1.260000,0.124000,0.000000,0.000000,0.000000,0.000000,0.000000,0.050000,0.100000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.200000,0.000000,0.400000,0.000000,0.000000,0.000000,0.000000,0.000000,0.010000,0.010000,0.030000,0.000000,NaN,0.000000,0.010000,NaN,0.000000,0.000000,0.001000,0.00100,0.000000,0.100000,0.108000,0.000000,0.000000,1.330000,1.240000,0.000000,0.000000,0.251,0.000000,22.200000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.100000,0.000000,0.000000,NaN,0.000000,-195.000000,0.000000,0.000000
25%,130.000000,13.000000,12.000000,32.000000,12.000000,10.000000,120.000000,NaN,15.225000,21.600000,6.800000,7.300000,0.775000,0.998800,NaN,324.500000,129.375000,2900.000000,NaN,0.610000,0.405750,0.070000,40.200000,3.095000,0.052500,0.030000,0.100000,1.200000,8.167000,0.300000,0.150000,0.060000,0.030000,0.000000,0.080000,0.000000,0.010000,0.010000,33.600000,0.450000,12.500000,0.260000,0.020000,0.010000,0.000000,0.268750,0.162500,0.020000,7.737500,7.600000,NaN,0.020000,0.031000,NaN,80.950000,0.182500,0.219750,0.00400,0.067500,0.500000,0.341500,0.010000,0.010000,45.400000,37.212500,1.500000,0.000000,0.251,1.984000,54.900000,0.032500,0.000200,0.020000,0.880000,0.000000,43.000000,0.185000,0.030000,0.155000,NaN,0.000000,30.000000,8.800000,0.200000
50%,130.000000,32.000000,30.000000,32.000000,26.000000,27.000000,285.000000,NaN,22.350000,41.500000,7.440000,7.700000,2.460000,1.000200,NaN,855.800000,186.000000,4300.000000,NaN,1.600000,1.600000,0.500000,170.000000,8.900000,0.140000,0.080000,0.565000,5.600000,18.055000,2.100000,4.200000,0.240000,0.180000,0.050000,0.300000,0.010000,0.040000,0.010000,43.500000,1.000000,73.650000,1.590000,0.100000,0.034000,0.000000,0.630000,0.355000,0.040000,29.100000,30.050000,NaN,0.065000,0.100000,NaN,154.000000,1.585000,1.028500,0.00650,0.745000,0.750000,0.582500,0.065000,0.032000,66.200000,64.885000,5.200000,0.995000,0.251,8.900000,162.000000,0.400000,0.000400,0.100000,2.730000,0.000000,102.500000,0.310000,0.365000,0.235000,NaN,0.000000,105.000000,33.500000,0.650000
75%,130.000000,41.000000,40.000000,33.000000,44.000000,40.000000,538.000000,NaN,26.800000,55.625000,8.160000,8.300000,9.007500,1.004400,NaN,2783.000000,602.500000,6450.000000,NaN,6.400000,5.000000,3.215000,599.250000,42.825000,0.340000,0.260000,2.385000,28.100000,89.652500,4.000000,94.025000,0.788750,0.770500,0.185000,1.200000,0.030000,0.120000,0.050000,58.400000,2.207500,591.000000,16.100000,0.327500,0.350000,0.000000,6.642500,0.745000,0.300000,106.050000,240.000000,NaN,0.315000,0.281500,NaN,347.200000,16.785000,4.028500,0.00875,3.192500,4.057500,0.960250,0.359750,0.064000,133.000000,121.275000,15.850000,4.755000,0.251,34.288000,370.500000,2.350000,0.000800,0.192500,6.500000,0.000000,219.750000,0.580000,1.400000,1.282500,NaN,11.875000,150.000000,149.000000,1.700000
max,131.000000,59.000000,59.000000,33.000000,59.000000,59.000000,970.000000,NaN,35.000000,102.000000,10.000000,9.900000,26.100000,1.029700,NaN,34970.000000,3760.000000,13000.000000,NaN,82.600000,25.200000,55.600000,10300.000000,913.000000,1.270000,1.270000,105.300000,1859.000000,2752.000000,90.400000,165.600000,412.630000,110.000000,235.500000,239.140000,0.700000,3.930000,3.500000,91.100000,35.000000,18960.000000,62.300000,50.400000,35.610000,2.140000,63.000000,3.760000,2464.662000,465.800000,5140.000000,NaN,8.200000,27.400000,NaN,4530.000000,11980.000000,78.340000,0.63900,38.450000,33.540000,5.380000,5.600000,0.214000,809.000000,707.300000,212.744000,6.070000,0.251,2566.000000,1784.000000,8380.000000,22.100000,1.200000,42.900000,4.060000,2410.000000,6.230000,275.710000,6.210000,NaN,33.400000,450.000000,10750.000000,100.700000

## いらない特徴を再度消す

再度、欠損値を見てみる

In [8]:
na_df = NA_counter(df_kyusyu_grid)
na_df

,都道府県名,所在地,東経（゜）,東経（′）,東経（″),北緯（゜）,北緯（′）,北緯（″),標高（ｍ）,水源種別,利用目的,井戸深度,採水標高,気温,水温,湧出量,水質（外観臭味）,ｐＨ,ＲｐＨ,Ｒｎ(マッヘ),比重,密度,蒸発残留物,電気伝導度,水比抵抗,ＥＨ,ＫＭｎＯ４消費,Ｈ＋,Ｌｉ＋,Na＋,Ｋ＋,Ｒｂ＋,Ｃｓ＋,ＮＨ４＋,Ｍｇ２＋,Ｃａ２＋,Ｓｒ２＋,Ｂａ２＋,Ａｌ３＋,Ｍｎ２＋,Ｆｅ２＋,Ｆｅ３＋,Ｔ−Ｆｅ,Ｃｕ２＋,Ｚｎ２＋,Ｐｂ２＋,Ｓｉ４＋,Ｆ−,Ｃｌ−,Ｂｒ−,I−,OH−,ＮＯ２−,ＮＯ３−,ＨＳ−,Ｓ２Ｏ３2−,ＨＳＯ４−,ＳＯ４２−,ＳＯ３２−,Ｈ２ＰＯ４−,ＨＰＯ４２−,ＰＯ４３−,ＨＣＯ３−,ＣＯ３２−,ＨＳｉＯ３−,ＳｉＯ３２−,ＢＯ２−,Ｈ２ＳＯ４,Ｈ３ＰＯ４,ＨＡｓＯ２,ＡｓＯ２-,ＳｉO２,Ｈ２ＳｉＯ３,ＨＢＯ２,dis.O2,Free H2S,free CO2,Ｔ−ＣＯ２,Ｔ−Ａｓ,Ｔ−Ｈｇ,Ｔ−Ｐ,Ｔ−Ｂ,単位,調査日,文献名,free H2s,free Co2,dis.co2,free H2S,ｄｉｓ．０２,ｆｒｅｅ Ｈ２Ｓ,ｆｒｅｅ ＣＯ２,Ｅh,freeCO2,Free H2s
n_nan,0,724,0,0,0,0,0,0,1421,0,0,1143,1536,970,44,1044,1519,23,935,1474,993,1536,727,1456,1489,1536,1259,1478,1204,82,84,1426,1426,756,91,70,1434,1526,1042,644,990,1420,517,1292,1313,1381,1391,852,16,1079,1222,1311,1327,1456,1386,1365,1494,140,1536,1446,1350,1536,157,1066,1280,1518,1364,1514,1500,1366,1494,1051,958,1147,1514,1535,1211,1481,1353,1415,1432,1287,790,94,0,1426,1414,1529,1282,1518,1536,1510,1499,1260,1476
%,0,0.471354,0,0,0,0,0,0,0.92513,0,0,0.744141,1,0.63151,0.0286458,0.679688,0.988932,0.014974,0.608724,0.959635,0.646484,1,0.473307,0.947917,0.969401,1,0.819661,0.96224,0.783854,0.0533854,0.0546875,0.928385,0.928385,0.492188,0.0592448,0.0455729,0.933594,0.99349,0.678385,0.419271,0.644531,0.924479,0.336589,0.841146,0.854818,0.899089,0.905599,0.554688,0.0104167,0.702474,0.795573,0.853516,0.863932,0.947917,0.902344,0.888672,0.972656,0.0911458,1,0.941406,0.878906,1,0.102214,0.69401,0.833333,0.988281,0.888021,0.985677,0.976562,0.889323,0.972656,0.684245,0.623698,0.746745,0.985677,0.999349,0.788411,0.964193,0.880859,0.921224,0.932292,0.837891,0.514323,0.0611979,0,0.928385,0.920573,0.995443,0.834635,0.988281,1,0.983073,0.975911,0.820312,0.960938
dtype,object,object,float64,float64,float64,float64,float64,float64,float64,object,object,object,float64,float64,float64,object,object,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,object,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,object,object,object,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64

全部欠損値のカラムがある

## そもそもすべてが欠損値のカラムは消してしまう

In [9]:
na_col_names = df_kyusyu_grid.columns[na_df.loc['%'] == 1] # drop n_nan rate 100% columns
df_kyusyu_grid = df_kyusyu_grid.drop(na_col_names, axis=1)
df_kyusyu_grid.head()

,都道府県名,所在地,東経（゜）,東経（′）,東経（″),北緯（゜）,北緯（′）,北緯（″),標高（ｍ）,水源種別,利用目的,井戸深度,気温,水温,湧出量,水質（外観臭味）,ｐＨ,ＲｐＨ,Ｒｎ(マッヘ),比重,蒸発残留物,電気伝導度,水比抵抗,ＫＭｎＯ４消費,Ｈ＋,Ｌｉ＋,Na＋,Ｋ＋,Ｒｂ＋,Ｃｓ＋,ＮＨ４＋,Ｍｇ２＋,Ｃａ２＋,Ｓｒ２＋,Ｂａ２＋,Ａｌ３＋,Ｍｎ２＋,Ｆｅ２＋,Ｆｅ３＋,Ｔ−Ｆｅ,Ｃｕ２＋,Ｚｎ２＋,Ｐｂ２＋,Ｓｉ４＋,Ｆ−,Ｃｌ−,Ｂｒ−,I−,OH−,ＮＯ２−,ＮＯ３−,ＨＳ−,Ｓ２Ｏ３2−,ＨＳＯ４−,ＳＯ４２−,Ｈ２ＰＯ４−,ＨＰＯ４２−,ＨＣＯ３−,ＣＯ３２−,ＨＳｉＯ３−,ＳｉＯ３２−,ＢＯ２−,Ｈ２ＳＯ４,Ｈ３ＰＯ４,ＨＡｓＯ２,ＡｓＯ２-,ＳｉO２,Ｈ２ＳｉＯ３,ＨＢＯ２,dis.O2,Free H2S,free CO2,Ｔ−ＣＯ２,Ｔ−Ａｓ,Ｔ−Ｈｇ,Ｔ−Ｐ,Ｔ−Ｂ,単位,調査日,文献名,free H2s,free Co2,dis.co2,free H2S,ｄｉｓ．０２,ｆｒｅｅ ＣＯ２,Ｅh,freeCO2,Free H2s
0,佐賀県,有明町廻里津,130.0,7.0,20.0,33.0,9.0,0.0,NaN,井戸,用水,NaN,NaN,23.6,NaN,NaN,7.3,7.5,NaN,NaN,NaN,NaN,NaN,3.7,NaN,NaN,16.0,4.9,NaN,NaN,0.1,4.6,8.0,NaN,NaN,NaN,NaN,0.06,0.05,NaN,NaN,NaN,NaN,NaN,NaN,7.8,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,67.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,68.6,NaN,NaN,NaN,NaN,3.5,NaN,NaN,NaN,0.13,NaN,NaN,1960/1,"筑後川下流平野の地下水,地調月報,1961",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,佐賀県,白石町,130.0,9.0,0.0,33.0,9.0,40.0,NaN,井戸,用水,NaN,NaN,20.0,NaN,NaN,7.3,7.4,NaN,NaN,NaN,NaN,NaN,3.8,NaN,NaN,24.9,7.0,NaN,NaN,0.2,4.0,6.8,NaN,NaN,NaN,NaN,0.15,0.00,NaN,NaN,NaN,NaN,NaN,NaN,7.8,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,86.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63.4,NaN,NaN,NaN,NaN,4.4,NaN,NaN,NaN,0.37,NaN,NaN,1960/1,"筑後川下流平野の地下水,地調月報,1961",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,佐賀県,白石町,130.0,8.0,30.0,33.0,10.0,50.0,NaN,井戸,用水,NaN,NaN,20.2,NaN,NaN,7.3,7.3,NaN,NaN,NaN,NaN,NaN,0.4,NaN,NaN,17.4,5.7,NaN,NaN,0.0,3.6,7.4,NaN,NaN,NaN,NaN,0,0.05,NaN,NaN,NaN,NaN,NaN,NaN,10.7,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,3.0,NaN,NaN,61.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,68.6,NaN,NaN,NaN,NaN,3.5,NaN,NaN,NaN,0.14,NaN,NaN,1960/1,"筑後川下流平野の地下水,地調月報,1961",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,佐賀県,福富町,130.0,11.0,20.0,33.0,11.0,0.0,NaN,井戸,用水,NaN,NaN,21.6,NaN,Ｈ2Ｓ臭,7.2,7.7,NaN,NaN,NaN,NaN,NaN,24.6,NaN,NaN,259.5,24.9,NaN,NaN,7.0,41.4,49.8,NaN,NaN,NaN,NaN,0.11,0.00,NaN,NaN,NaN,NaN,NaN,NaN,419.1,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,297.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.65,NaN,NaN,1960/1,"筑後川下流平野の地下水,地調月報,1961",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,佐賀県,牛津町,130.0,12.0,0.0,33.0,14.0,20.0,NaN,井戸,用水,151.5,NaN,19.2,NaN,NaN,7.7,7.7,NaN,NaN,NaN,NaN,NaN,1.7,NaN,NaN,26.1,1.7,NaN,NaN,0.3,5.2,18.6,NaN,NaN,NaN,NaN,0,0.02,NaN,NaN,NaN,NaN,NaN,NaN,12.1,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,113.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.4,NaN,NaN,NaN,NaN,1.7,NaN,NaN,NaN,0.16,NaN,NaN,1960/1,"筑後川下流平野の地下水,地調月報,1961",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
NA_counter(df_kyusyu_grid)

,都道府県名,所在地,東経（゜）,東経（′）,東経（″),北緯（゜）,北緯（′）,北緯（″),標高（ｍ）,水源種別,利用目的,井戸深度,気温,水温,湧出量,水質（外観臭味）,ｐＨ,ＲｐＨ,Ｒｎ(マッヘ),比重,蒸発残留物,電気伝導度,水比抵抗,ＫＭｎＯ４消費,Ｈ＋,Ｌｉ＋,Na＋,Ｋ＋,Ｒｂ＋,Ｃｓ＋,ＮＨ４＋,Ｍｇ２＋,Ｃａ２＋,Ｓｒ２＋,Ｂａ２＋,Ａｌ３＋,Ｍｎ２＋,Ｆｅ２＋,Ｆｅ３＋,Ｔ−Ｆｅ,Ｃｕ２＋,Ｚｎ２＋,Ｐｂ２＋,Ｓｉ４＋,Ｆ−,Ｃｌ−,Ｂｒ−,I−,OH−,ＮＯ２−,ＮＯ３−,ＨＳ−,Ｓ２Ｏ３2−,ＨＳＯ４−,ＳＯ４２−,Ｈ２ＰＯ４−,ＨＰＯ４２−,ＨＣＯ３−,ＣＯ３２−,ＨＳｉＯ３−,ＳｉＯ３２−,ＢＯ２−,Ｈ２ＳＯ４,Ｈ３ＰＯ４,ＨＡｓＯ２,ＡｓＯ２-,ＳｉO２,Ｈ２ＳｉＯ３,ＨＢＯ２,dis.O2,Free H2S,free CO2,Ｔ−ＣＯ２,Ｔ−Ａｓ,Ｔ−Ｈｇ,Ｔ−Ｐ,Ｔ−Ｂ,単位,調査日,文献名,free H2s,free Co2,dis.co2,free H2S,ｄｉｓ．０２,ｆｒｅｅ ＣＯ２,Ｅh,freeCO2,Free H2s
n_nan,0,724,0,0,0,0,0,0,1421,0,0,1143,970,44,1044,1519,23,935,1474,993,727,1456,1489,1259,1478,1204,82,84,1426,1426,756,91,70,1434,1526,1042,644,990,1420,517,1292,1313,1381,1391,852,16,1079,1222,1311,1327,1456,1386,1365,1494,140,1446,1350,157,1066,1280,1518,1364,1514,1500,1366,1494,1051,958,1147,1514,1535,1211,1481,1353,1415,1432,1287,790,94,0,1426,1414,1529,1282,1518,1510,1499,1260,1476
%,0,0.471354,0,0,0,0,0,0,0.92513,0,0,0.744141,0.63151,0.0286458,0.679688,0.988932,0.014974,0.608724,0.959635,0.646484,0.473307,0.947917,0.969401,0.819661,0.96224,0.783854,0.0533854,0.0546875,0.928385,0.928385,0.492188,0.0592448,0.0455729,0.933594,0.99349,0.678385,0.419271,0.644531,0.924479,0.336589,0.841146,0.854818,0.899089,0.905599,0.554688,0.0104167,0.702474,0.795573,0.853516,0.863932,0.947917,0.902344,0.888672,0.972656,0.0911458,0.941406,0.878906,0.102214,0.69401,0.833333,0.988281,0.888021,0.985677,0.976562,0.889323,0.972656,0.684245,0.623698,0.746745,0.985677,0.999349,0.788411,0.964193,0.880859,0.921224,0.932292,0.837891,0.514323,0.0611979,0,0.928385,0.920573,0.995443,0.834635,0.988281,0.983073,0.975911,0.820312,0.960938
dtype,object,object,float64,float64,float64,float64,float64,float64,float64,object,object,object,float64,float64,object,object,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,object,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,object,object,object,float64,float64,float64,float64,float64,float64,float64,float64,float64

## イオン濃度の欠損値には0埋めする

イオン濃度が欠損しているということは、その温泉の売り成分ではないと考えられるため

In [11]:
iron_names = df_kyusyu_grid.iloc[:, 24:-12].columns
iron_names_replace_0 = {str(n):0 for n in iron_names}
df_kyusyu_grid = df_kyusyu_grid.fillna(iron_names_replace_0)

In [12]:
df_kyusyu_grid.head()

,都道府県名,所在地,東経（゜）,東経（′）,東経（″),北緯（゜）,北緯（′）,北緯（″),標高（ｍ）,水源種別,利用目的,井戸深度,気温,水温,湧出量,水質（外観臭味）,ｐＨ,ＲｐＨ,Ｒｎ(マッヘ),比重,蒸発残留物,電気伝導度,水比抵抗,ＫＭｎＯ４消費,Ｈ＋,Ｌｉ＋,Na＋,Ｋ＋,Ｒｂ＋,Ｃｓ＋,ＮＨ４＋,Ｍｇ２＋,Ｃａ２＋,Ｓｒ２＋,Ｂａ２＋,Ａｌ３＋,Ｍｎ２＋,Ｆｅ２＋,Ｆｅ３＋,Ｔ−Ｆｅ,Ｃｕ２＋,Ｚｎ２＋,Ｐｂ２＋,Ｓｉ４＋,Ｆ−,Ｃｌ−,Ｂｒ−,I−,OH−,ＮＯ２−,ＮＯ３−,ＨＳ−,Ｓ２Ｏ３2−,ＨＳＯ４−,ＳＯ４２−,Ｈ２ＰＯ４−,ＨＰＯ４２−,ＨＣＯ３−,ＣＯ３２−,ＨＳｉＯ３−,ＳｉＯ３２−,ＢＯ２−,Ｈ２ＳＯ４,Ｈ３ＰＯ４,ＨＡｓＯ２,ＡｓＯ２-,ＳｉO２,Ｈ２ＳｉＯ３,ＨＢＯ２,dis.O2,Free H2S,free CO2,Ｔ−ＣＯ２,Ｔ−Ａｓ,Ｔ−Ｈｇ,Ｔ−Ｐ,Ｔ−Ｂ,単位,調査日,文献名,free H2s,free Co2,dis.co2,free H2S,ｄｉｓ．０２,ｆｒｅｅ ＣＯ２,Ｅh,freeCO2,Free H2s
0,佐賀県,有明町廻里津,130.0,7.0,20.0,33.0,9.0,0.0,NaN,井戸,用水,NaN,NaN,23.6,NaN,NaN,7.3,7.5,NaN,NaN,NaN,NaN,NaN,3.7,0.0,0.0,16.0,4.9,0.0,0.0,0.1,4.6,8.0,0.0,0.0,0.0,0.0,0.06,0.05,0.0,0.0,0.0,0.0,0.0,0.0,7.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,67.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,68.6,0.0,0.0,0.0,0.0,3.5,0.0,0.0,0.0,0.13,0.0,NaN,1960/1,"筑後川下流平野の地下水,地調月報,1961",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,佐賀県,白石町,130.0,9.0,0.0,33.0,9.0,40.0,NaN,井戸,用水,NaN,NaN,20.0,NaN,NaN,7.3,7.4,NaN,NaN,NaN,NaN,NaN,3.8,0.0,0.0,24.9,7.0,0.0,0.0,0.2,4.0,6.8,0.0,0.0,0.0,0.0,0.15,0.00,0.0,0.0,0.0,0.0,0.0,0.0,7.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,86.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,63.4,0.0,0.0,0.0,0.0,4.4,0.0,0.0,0.0,0.37,0.0,NaN,1960/1,"筑後川下流平野の地下水,地調月報,1961",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,佐賀県,白石町,130.0,8.0,30.0,33.0,10.0,50.0,NaN,井戸,用水,NaN,NaN,20.2,NaN,NaN,7.3,7.3,NaN,NaN,NaN,NaN,NaN,0.4,0.0,0.0,17.4,5.7,0.0,0.0,0.0,3.6,7.4,0.0,0.0,0.0,0.0,0,0.05,0.0,0.0,0.0,0.0,0.0,0.0,10.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,61.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,68.6,0.0,0.0,0.0,0.0,3.5,0.0,0.0,0.0,0.14,0.0,NaN,1960/1,"筑後川下流平野の地下水,地調月報,1961",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,佐賀県,福富町,130.0,11.0,20.0,33.0,11.0,0.0,NaN,井戸,用水,NaN,NaN,21.6,NaN,Ｈ2Ｓ臭,7.2,7.7,NaN,NaN,NaN,NaN,NaN,24.6,0.0,0.0,259.5,24.9,0.0,0.0,7.0,41.4,49.8,0.0,0.0,0.0,0.0,0.11,0.00,0.0,0.0,0.0,0.0,0.0,0.0,419.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,297.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,55.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.65,0.0,NaN,1960/1,"筑後川下流平野の地下水,地調月報,1961",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,佐賀県,牛津町,130.0,12.0,0.0,33.0,14.0,20.0,NaN,井戸,用水,151.5,NaN,19.2,NaN,NaN,7.7,7.7,NaN,NaN,NaN,NaN,NaN,1.7,0.0,0.0,26.1,1.7,0.0,0.0,0.3,5.2,18.6,0.0,0.0,0.0,0.0,0,0.02,0.0,0.0,0.0,0.0,0.0,0.0,12.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,113.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25.4,0.0,0.0,0.0,0.0,1.7,0.0,0.0,0.0,0.16,0.0,NaN,1960/1,"筑後川下流平野の地下水,地調月報,1961",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## イオンの欠損値を0埋めしたところで、ほかの欠損値も確認

In [13]:
NA_counter(df_kyusyu_grid)

,都道府県名,所在地,東経（゜）,東経（′）,東経（″),北緯（゜）,北緯（′）,北緯（″),標高（ｍ）,水源種別,利用目的,井戸深度,気温,水温,湧出量,水質（外観臭味）,ｐＨ,ＲｐＨ,Ｒｎ(マッヘ),比重,蒸発残留物,電気伝導度,水比抵抗,ＫＭｎＯ４消費,Ｈ＋,Ｌｉ＋,Na＋,Ｋ＋,Ｒｂ＋,Ｃｓ＋,ＮＨ４＋,Ｍｇ２＋,Ｃａ２＋,Ｓｒ２＋,Ｂａ２＋,Ａｌ３＋,Ｍｎ２＋,Ｆｅ２＋,Ｆｅ３＋,Ｔ−Ｆｅ,Ｃｕ２＋,Ｚｎ２＋,Ｐｂ２＋,Ｓｉ４＋,Ｆ−,Ｃｌ−,Ｂｒ−,I−,OH−,ＮＯ２−,ＮＯ３−,ＨＳ−,Ｓ２Ｏ３2−,ＨＳＯ４−,ＳＯ４２−,Ｈ２ＰＯ４−,ＨＰＯ４２−,ＨＣＯ３−,ＣＯ３２−,ＨＳｉＯ３−,ＳｉＯ３２−,ＢＯ２−,Ｈ２ＳＯ４,Ｈ３ＰＯ４,ＨＡｓＯ２,ＡｓＯ２-,ＳｉO２,Ｈ２ＳｉＯ３,ＨＢＯ２,dis.O2,Free H2S,free CO2,Ｔ−ＣＯ２,Ｔ−Ａｓ,Ｔ−Ｈｇ,Ｔ−Ｐ,Ｔ−Ｂ,単位,調査日,文献名,free H2s,free Co2,dis.co2,free H2S,ｄｉｓ．０２,ｆｒｅｅ ＣＯ２,Ｅh,freeCO2,Free H2s
n_nan,0,724,0,0,0,0,0,0,1421,0,0,1143,970,44,1044,1519,23,935,1474,993,727,1456,1489,1259,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,790,94,0,1426,1414,1529,1282,1518,1510,1499,1260,1476
%,0,0.471354,0,0,0,0,0,0,0.92513,0,0,0.744141,0.63151,0.0286458,0.679688,0.988932,0.014974,0.608724,0.959635,0.646484,0.473307,0.947917,0.969401,0.819661,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.514323,0.0611979,0,0.928385,0.920573,0.995443,0.834635,0.988281,0.983073,0.975911,0.820312,0.960938
dtype,object,object,float64,float64,float64,float64,float64,float64,float64,object,object,object,float64,float64,object,object,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,object,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,object,object,object,float64,float64,float64,float64,float64,float64,float64,float64,float64

標高・井戸深度・気温・水質：欠損が多いし重要じゃなさそうなので消してヨシ！<br>
イオン濃度と相関がありそうな比重・電気伝導度・水比抵抗・KMnO4消費も消す.<br>
よく分からんのがRpH, Rn, 蒸発残留物, free H2s以降. この辺は9割欠損しているので無くてもいいような気はする.<br>
free H2Sが3つあるのもよく分からん. イオン以降はすべて消してもいいかもしれん.<br>

とりあえず可能な限りdropしてみる.

In [14]:
df_kyusyu_grid = df_kyusyu_grid.iloc[:, :-12]
df_kyusyu_grid.head()

,都道府県名,所在地,東経（゜）,東経（′）,東経（″),北緯（゜）,北緯（′）,北緯（″),標高（ｍ）,水源種別,利用目的,井戸深度,気温,水温,湧出量,水質（外観臭味）,ｐＨ,ＲｐＨ,Ｒｎ(マッヘ),比重,蒸発残留物,電気伝導度,水比抵抗,ＫＭｎＯ４消費,Ｈ＋,Ｌｉ＋,Na＋,Ｋ＋,Ｒｂ＋,Ｃｓ＋,ＮＨ４＋,Ｍｇ２＋,Ｃａ２＋,Ｓｒ２＋,Ｂａ２＋,Ａｌ３＋,Ｍｎ２＋,Ｆｅ２＋,Ｆｅ３＋,Ｔ−Ｆｅ,Ｃｕ２＋,Ｚｎ２＋,Ｐｂ２＋,Ｓｉ４＋,Ｆ−,Ｃｌ−,Ｂｒ−,I−,OH−,ＮＯ２−,ＮＯ３−,ＨＳ−,Ｓ２Ｏ３2−,ＨＳＯ４−,ＳＯ４２−,Ｈ２ＰＯ４−,ＨＰＯ４２−,ＨＣＯ３−,ＣＯ３２−,ＨＳｉＯ３−,ＳｉＯ３２−,ＢＯ２−,Ｈ２ＳＯ４,Ｈ３ＰＯ４,ＨＡｓＯ２,ＡｓＯ２-,ＳｉO２,Ｈ２ＳｉＯ３,ＨＢＯ２,dis.O2,Free H2S,free CO2,Ｔ−ＣＯ２,Ｔ−Ａｓ,Ｔ−Ｈｇ,Ｔ−Ｐ,Ｔ−Ｂ
0,佐賀県,有明町廻里津,130.0,7.0,20.0,33.0,9.0,0.0,NaN,井戸,用水,NaN,NaN,23.6,NaN,NaN,7.3,7.5,NaN,NaN,NaN,NaN,NaN,3.7,0.0,0.0,16.0,4.9,0.0,0.0,0.1,4.6,8.0,0.0,0.0,0.0,0.0,0.06,0.05,0.0,0.0,0.0,0.0,0.0,0.0,7.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,67.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,68.6,0.0,0.0,0.0,0.0,3.5,0.0,0.0,0.0,0.13,0.0
1,佐賀県,白石町,130.0,9.0,0.0,33.0,9.0,40.0,NaN,井戸,用水,NaN,NaN,20.0,NaN,NaN,7.3,7.4,NaN,NaN,NaN,NaN,NaN,3.8,0.0,0.0,24.9,7.0,0.0,0.0,0.2,4.0,6.8,0.0,0.0,0.0,0.0,0.15,0.00,0.0,0.0,0.0,0.0,0.0,0.0,7.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,86.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,63.4,0.0,0.0,0.0,0.0,4.4,0.0,0.0,0.0,0.37,0.0
2,佐賀県,白石町,130.0,8.0,30.0,33.0,10.0,50.0,NaN,井戸,用水,NaN,NaN,20.2,NaN,NaN,7.3,7.3,NaN,NaN,NaN,NaN,NaN,0.4,0.0,0.0,17.4,5.7,0.0,0.0,0.0,3.6,7.4,0.0,0.0,0.0,0.0,0,0.05,0.0,0.0,0.0,0.0,0.0,0.0,10.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,61.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,68.6,0.0,0.0,0.0,0.0,3.5,0.0,0.0,0.0,0.14,0.0
3,佐賀県,福富町,130.0,11.0,20.0,33.0,11.0,0.0,NaN,井戸,用水,NaN,NaN,21.6,NaN,Ｈ2Ｓ臭,7.2,7.7,NaN,NaN,NaN,NaN,NaN,24.6,0.0,0.0,259.5,24.9,0.0,0.0,7.0,41.4,49.8,0.0,0.0,0.0,0.0,0.11,0.00,0.0,0.0,0.0,0.0,0.0,0.0,419.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,297.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,55.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.65,0.0
4,佐賀県,牛津町,130.0,12.0,0.0,33.0,14.0,20.0,NaN,井戸,用水,151.5,NaN,19.2,NaN,NaN,7.7,7.7,NaN,NaN,NaN,NaN,NaN,1.7,0.0,0.0,26.1,1.7,0.0,0.0,0.3,5.2,18.6,0.0,0.0,0.0,0.0,0,0.02,0.0,0.0,0.0,0.0,0.0,0.0,12.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,113.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25.4,0.0,0.0,0.0,0.0,1.7,0.0,0.0,0.0,0.16,0.0

In [15]:
NA_counter(df_kyusyu_grid)

,都道府県名,所在地,東経（゜）,東経（′）,東経（″),北緯（゜）,北緯（′）,北緯（″),標高（ｍ）,水源種別,利用目的,井戸深度,気温,水温,湧出量,水質（外観臭味）,ｐＨ,ＲｐＨ,Ｒｎ(マッヘ),比重,蒸発残留物,電気伝導度,水比抵抗,ＫＭｎＯ４消費,Ｈ＋,Ｌｉ＋,Na＋,Ｋ＋,Ｒｂ＋,Ｃｓ＋,ＮＨ４＋,Ｍｇ２＋,Ｃａ２＋,Ｓｒ２＋,Ｂａ２＋,Ａｌ３＋,Ｍｎ２＋,Ｆｅ２＋,Ｆｅ３＋,Ｔ−Ｆｅ,Ｃｕ２＋,Ｚｎ２＋,Ｐｂ２＋,Ｓｉ４＋,Ｆ−,Ｃｌ−,Ｂｒ−,I−,OH−,ＮＯ２−,ＮＯ３−,ＨＳ−,Ｓ２Ｏ３2−,ＨＳＯ４−,ＳＯ４２−,Ｈ２ＰＯ４−,ＨＰＯ４２−,ＨＣＯ３−,ＣＯ３２−,ＨＳｉＯ３−,ＳｉＯ３２−,ＢＯ２−,Ｈ２ＳＯ４,Ｈ３ＰＯ４,ＨＡｓＯ２,ＡｓＯ２-,ＳｉO２,Ｈ２ＳｉＯ３,ＨＢＯ２,dis.O2,Free H2S,free CO2,Ｔ−ＣＯ２,Ｔ−Ａｓ,Ｔ−Ｈｇ,Ｔ−Ｐ,Ｔ−Ｂ
n_nan,0,724,0,0,0,0,0,0,1421,0,0,1143,970,44,1044,1519,23,935,1474,993,727,1456,1489,1259,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
%,0,0.471354,0,0,0,0,0,0,0.92513,0,0,0.744141,0.63151,0.0286458,0.679688,0.988932,0.014974,0.608724,0.959635,0.646484,0.473307,0.947917,0.969401,0.819661,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
dtype,object,object,float64,float64,float64,float64,float64,float64,float64,object,object,object,float64,float64,object,object,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,object,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64

In [16]:
import lightgbm as lgb
from sklearn.model_selection import train_test_split